### ISSUE TITLE
Package breaks on repo migrations and doesn't run

### ISSUE THREAD

**Issue by jimjimvalkema** [dappnode/DNP_IPFS#109]
**Describe the bug**
The package somehow migrates the repo to v15 but then runs ipfs on v14 and then crashes
```
ipfs version 0.22.0
Found IPFS fs-repo at /data/ipfs
Found fs-repo version 14 at /data/ipfs
2023/09/02 17:59:43 Looking for suitable migration binaries.
2023/09/02 17:59:43 Need 1 migrations, downloading.
2023/09/02 17:59:43 Downloading migration: fs-repo-14-to-15...
2023/09/02 17:59:43 Downloaded and unpacked migration: /tmp/migrations867660951/fs-repo-14-to-15 (v1.0.0)
2023/09/02 17:59:43 Running migration fs-repo-14-to-15 ...
2023/09/02 17:59:43   => Running: /tmp/migrations867660951/fs-repo-14-to-15 -path=/data/ipfs -verbose=true
applying 14-to-15 repo migration
locking repo at "/data/ipfs"
  - verifying version is '14'
> Upgrading config to new format
updated version file
Migration 14 to 15 succeeded
2023/09/02 17:59:43 Success: fs-repo migrated to version 15.
Error: Your programs version (14) is lower than your repos (15).
Please update ipfs to a version that supports the existing repo, or run
a migration in reverse.
```

See https://github.com/ipfs/fs-repo-migrations/blob/master/run.md for details.`
 

**To Reproduce**
upgrade to 0.2.20 from a previous version with a existing repo

**Expected behavior**

**Screenshots**

**DAppNode version:**

Core DAppNode Packages versions
bind.dnp.dappnode.eth: 0.2.6
core.dnp.dappnode.eth: 0.2.77
dappmanager.dnp.dappnode.eth: 0.2.72, commit: 26bbe6f9
https.dnp.dappnode.eth: 0.2.1
ipfs.dnp.dappnode.eth: 0.2.20
wifi.dnp.dappnode.eth: 0.2.8
wireguard.dnp.dappnode.eth: 0.1.2
System info
dockerComposeVersion: 1.25.5
dockerServerVersion: 20.10.6
dockerCliVersion: 20.10.6
os: debian
versionCodename: bullseye
architecture: amd64
kernel: 5.10.0-21-amd64

- Package version: 
- OS: 
- Browser 

**Additional context**

**Comment by pablomendezroyo** [comment]
@davidrhodus 

did you update ipfs to the latest version? http://my.dappnode/installer/dnp/ipfs.dnp.dappnode.eth
