### ISSUE TITLE
entrypoint.sh may break due to ipfs migration

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_IPFS#47]
## Context

DAppNode is overwriting the original `entrypoint.sh` from the official IPFS docker image: 

- Official docker image: https://github.com/ipfs/go-ipfs/blob/master/Dockerfile
- Official entrypoint: https://github.com/dappnode/DNP_IPFS/blob/dappnodebot/bump-upstream/go-ipfs%40v0.9.0-rc2/build/original_entrypoint.sh
- Dappnode entrypoint: https://github.com/dappnode/DNP_IPFS/blob/master/build/start_ipfs

## The error
The edited entrypoint uses the `ipfs` binary to edit the configuration at some point BEFORE the daemon `ipfs daemon --migrate=true` which executes a [MIGRATION](https://github.com/ipfs/go-ipfs/blob/eda8b43a28b1979ac08617b9a945c37602c5b79a/Dockerfile#L110) if necessary (in this release will be mandatory) resulting in an error:
```
ipfs repo needs migration
```

## Solution

Execute `ipfs daemon --migrate=true` before applying any custom configuration with the binary `ipfs` which may result into an error

Consider
- [ ] Removing custom configuration due to the upcoming IPFS optional feature
- [ ] Research for a solution to check if the migration was done, if it was then execute custom configuration as ususal. If it was not then do migration before custom configuration

**Comment by dapplion** [comment]
CC: @eduadiez

**Comment by pablomendezroyo** [comment]
## UPDATE
Fixed adding tool `fs-repo-migration` 

https://github.com/dappnode/DNP_IPFS/blob/5159251935d4a701d3f1d5718006c8829d7bb5c7/build/dappnode_entrypoint.sh#L11
https://github.com/dappnode/DNP_IPFS/blob/5159251935d4a701d3f1d5718006c8829d7bb5c7/build/Dockerfile#L4

To research:
- [ ] Determine when to run this tool. Ideally only when necessary
