### ISSUE TITLE
IPFS shows restarting constantly

### ISSUE THREAD

**Issue by newbie1979** [dappnode/DNP_IPFS#60]
In my daapnode I see IPFS as "restarting"
Logs show
Found IPFS fs-repo at /data/ipfs
Error: failed to parse multiaddr "": empty multiaddr

Support - auto diagnose shows
Core DAppNode Packages ipfs.dnp.dappnode.eth are not running
Make sure the disk is not too full. If so DAppNode automatically stops the IPFS package to prevent it from becoming un-usable
Go to the System tab and restart each stopped DAppNode Package. Please inspect the logs to understand cause and report it if it was not expected

Ports 
4001 | TCP | Ipfs | Closed for API

**Comment by 3alpha** [comment]
Hey, more information would really be useful.
