### ISSUE TITLE
IPFS Restart Error

### ISSUE THREAD

**Issue by Mattyreed1** [dappnode/DNP_IPFS#66]
Restarting IPFS in Dappnode and getting the following error:

ipfs version 0.9.1
Found IPFS fs-repo at /data/ipfs
Error: failed to parse multiaddr "": empty multiaddr

**Comment by tropicar** [comment]
Firstly, sorry for the delayed answer. I don't know if you can access the dappnode UI. If you can you go to http://my.dappnode/#/support/report or DAppNode UI > Support > Report > copy all that information related to versions.
I think that ipfs version refers to the upstream version (ipfs version, not dappnode packageversion)and that means that you are using an older version.l

I would recommend you to install the latest version, you can do it if you go to the dappstore and paste `/ipfs/QmQJD7N3R2jQawNHwfRrVercEeWeyBJgG8PjVZE7ggam9e` or by clicking on http://my.dappnode/#/installer/%2Fipfs%2Fbafybeia5c5cg723dpypbz2mez6ge4ts5ixusi6sba2bszjrxk75cmw32du 
(you have to click on the advanced option and enable both bypass options) and click on update.

**Comment by pablomendezroyo** [comment]
Removing the ipfs volumes should fix the issue. Then make sure that your dappnode ipfs package is updated
