### ISSUE TITLE
Errors in IPFS status in the Dashboard while IPFS logs are  ok

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_IPFS#7]
Sometimes an IPFS down error appears in the dashboard with  IPFS logs apparently ok, also if i try to install a package, there is an error in the screen, but i can succesfully install the package, so apparently there is errors showed in screen but everything works. After restarting it was behaving the same way . Only after disconnecting and connecting again to the VPN the error dissapeared. 

![image](https://user-images.githubusercontent.com/21328788/46690694-46d2fa00-cc03-11e8-98b0-61ce6a008287.png)

![image](https://user-images.githubusercontent.com/21328788/46690703-4b97ae00-cc03-11e8-8540-c2ce7ad68b29.png)

![image](https://user-images.githubusercontent.com/21328788/46690708-4f2b3500-cc03-11e8-9b47-ad436c30c15c.png)

![image](https://user-images.githubusercontent.com/21328788/46690768-741fa800-cc03-11e8-8a89-54bd029a7406.png)

**Comment by dapplion** [comment]
The IPFS connection verifier was reworked in the last version of the DNP_ADMIN. Can you please share if have you experienced this error again? Thank you!

**Comment by dapplion** [comment]
@Shelpin If so, please close this issue and open a new one in the https://github.com/dappnode/DNP_ADMIN repo

**Comment by Shelpin** [comment]
Never, saw it again, closing it .... Thanks!
