### ISSUE TITLE
IPFS crashes my modem

### ISSUE THREAD

**Issue by MeganerdNL** [dappnode/DNP_IPFS#71]
IPFS frequently crashes my modem. No internet whatsoever for minutes. According tho [this issue](https://github.com/ipfs/kubo/issues/3320) it has to do with an option "LIBP2P_TCP_REUSEPORT" that has to be set to _false_. However I cannot change it anywhere. I tried to set a global environment variable in /etc/environment 

`LIBP2P_TCP_REUSEPORT=false`

However that does not seem to work.

Version: 0.2.16 (v0.12.1 upstream)

**Comment by MeganerdNL** [comment]
Update on this:

I managed to add a environment variable in the following file:

`/usr/src/dappnode/DNCORE/docker-compose-ipfs.yml`

adding

`LIBP2P_TCP_REUSEPORT=false`

to this file under _environment_.

This caused my modem not to crash anymore. Maybe add this standard as an option?

**Comment by pablomendezroyo** [comment]
@MeganerdNL Thankyou for the research! we will take a look and if its convenient, we will introduce this feature in the `setup-wizard` to allow users to set this ipfs mode directly from the UI.

Remember that if your IPFS is crashing your router you can always choose IPFS remote at **system > repository > IPFS > remote**, and switch off the IPFS Package

**Comment by MeganerdNL** [comment]
> @MeganerdNL Thankyou for the research! we will take a look and if its convenient, we will introduce this feature in the `setup-wizard` to allow users to set this ipfs mode directly from the UI.
> 
> Remember that if your IPFS is crashing your router you can always choose IPFS remote at **system > repository > IPFS > remote**, and switch off the IPFS Package

Thanks. I ended up switching to remote IPFS because with **LIBP2P_TCP_REUSEPORT=false** it only took longer to crash, but it did crash. IPFS people are aware of it (I'm not the only one): see the link in the first post. My router is behid the modem that crashes. Router is fine (running OPNsense).

**Comment by pablomendezroyo** [comment]
> Are there any disadvantages of disabling IPFS?

The disadvantages are centrallization, you are using an IPFS node supported by us instead of yours. We are working on making ipfs local more resilient
