### ISSUE TITLE
Where's the webui?

### ISSUE THREAD

**Issue by MeganerdNL** [dappnode/DNP_IPFS#94]
There is a link to the WebUI in Package Info, but it loads a blank page...  so there seems to be something on http://ipfs.dappnode:5001/webui - but empty.

There used to be a nice interface. Where is it? I can't find it's removal in the Changelogs.

**Edit: Nevermind: apparently  I had to reset IPFS by deleting it's volumes... Everything works now.**

**Comment by pablomendezroyo** [comment]
good to know you made it work. I suggest you to add the dappnode ipfs peer so you can fetch releases easier, you can do this by going to **packages** > **system packages** > **ipfs** > **config** > add dappnode ipfs peer
